### ISSUE TITLE
undef caller is given when using LOG<CARP> functions in easy mode

### ISSUE THREAD

**Issue by JC001010** [polettix/Log-Log4perl-Tiny#13]
Hi,

I believe I found a bug with the latest release. When using LOGCONFESS, LOGCROAK, LOGCARP, etc. in easy mode, the log level is "WARN" instead of FATAL and the caller's name is "*undef" instead of the name of the function that called the LOG* function.

Example:

```
#Here I get 'WARN - *undef - This is a test at ./test.pl'
LOGCONFESS "This is a test";

#Here I get 'WARN - *undef - This is a test at ./test.pl'
LOGCROAK "This is a test";

#Here I get 'FATAL - main - This is a test', which is expected.
LOGDIE "This is a test";
```

Thank you

**Comment by polettix** [comment]
Hi! Should be fixed by 1.6.4, thanks for reporting this!
