### ISSUE TITLE
Cannot adjust caller level

### ISSUE THREAD

**Issue by jwittkoski** [polettix/Log-Log4perl-Tiny#2]
Currently `Log::Log4perl::Tiny` caller related placeholders are not accurate when using modules like `Dancer::Logger::Log4perl`.

When other modules such as `Dancer::Logger::Log4perl` sit between the "original" caller and `Log::Log4perl::Tiny`, the caller depth needs to be adjusted so that placeholders reference the original caller details and not the intermediate module.

`Log::Log4perl` has `caller_depth` which intermediate modules can adjust to accommodate this situation, but `Log::Log4perl::Tiny` does not.

See related https://github.com/polettix/Dancer-Logger-Log4perl/pull/4#issuecomment-10327171

**Comment by polettix** [comment]
Also created as [https://rt.cpan.org/Ticket/Display.html?id=101450](101450 in RT)

**Comment by polettix** [comment]
Well... *better late than never*, isn't it?

I managed to implement something to this regard, but on the way I figured that the different expansion thingies playing with `caller()` were a bit broken (or so I do see them now). Before doing more harm than benefit, I'd like to hear from you about it.

I'm about to push new stuff in a new branch, I'll let you know when it's there. If you think I'm breaking anything, we can first of all discuss what the expectation is, then plan some way to allow for a smooth transition.

**Comment by polettix** [comment]
OK, branch feature/caller_depth (https://github.com/polettix/Log-Log4perl-Tiny/tree/feature/caller_depth) contains the proposed changes and tests. Please give it a try and let me know your feedback!

**Comment by polettix** [comment]
I created a new branch [feature/caller_depth-2](https://github.com/polettix/Log-Log4perl-Tiny/tree/feature/caller_depth-2) with the proposals rebased to the latest modifications. There is an added (author) test that checks alignment against Log::Log4perl, so I'm going to mark this as "official" because Log::Log4perl::Tiny always aimed at compatibility with that (so that users can easily switch to Log::Log4perl should they need additional features).

**Comment by polettix** [comment]
Merged branch feature/caller_depth-2 and migrated the distribution system to Milla. Tests are passing in Travis-CI. I'm about to send a trial release 1.3.1 for doing a few preliminary checks and then I'll release 1.4.0.

**Comment by polettix** [comment]
Released with 1.4.0.
