### ISSUE TITLE
/bin/bash may not exist

### ISSUE THREAD

**Issue by eserte** [polettix/Log-Log4perl-Tiny#6]
t/layout-compare.t in Log-Log4perl-Tiny-1.3.1-TRIAL fails e.g. on FreeBSD systems:
```
Can't exec /bin/bash at t/layout-compare.t line 1.
t/layout-compare.t ....... 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
```
In fact, there's no guarantee on Unix systems that bash exists at all. However, you can rely that /bin/sh exists.

If bash is installed on FreeBSD systems, then it's located as /usr/local/bin/bash. This is probably true for other BSD systems, too.

**Comment by polettix** [comment]
Well, I think I owe you a beer or two for all the first-person debugging you provide, thanks!

I'll just deactivate that test, it's actually only meant for developing and anyone should come here on Github to participate.

**Comment by polettix** [comment]
Tests seem right now

**Comment by eserte** [comment]
> I couldn't resist... re-implemented the test in Perl. Hubris over Laziness!

Rewriting in Perl is often a good decision.
Tests indeed look good now: http://matrix.cpantesters.org/?dist=Log-Log4perl-Tiny%201.3.2-TRIAL
